# Default values for ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/idata-corporation/pipeline-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "8f76f3-amd64"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    # TODO - change this value to your host
    - host: ui.poc.idatadev.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 2
    memory: 256Mi
  requests:
    cpu: 1
    memory: 128Mi

env:
  # TODO - change this value to your host
  REACT_APP_API_GATEWAY_ENDPOINT: https://pipeline.poc.idatadev.cloud
  REACT_APP_X_API_KEY: 1847626a-5b46-4d43-827c-25f323d9201b
  REACT_APP_REQUIRE_LOGIN: "false"
  REACT_APP_COGNITO_USER_APP_CLIENT_ID: NA
  REACT_APP_COGNITO_USER_POOL_ID: NA