spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  server:
    tomcat:
      connection-timeout: "600000"
  management:
    health:
      probes:
        enabled: "true"
      livenessState:
        enabled: "true"
      readinessState:
        enabled: "true"
schedule:
  checkFileNotifierQueue: "5000"
  findJobsToStart: "5000"
  checkDatabaseSourceQueries: "30000"
  checkCDCMessageQueue: "10000"
environment: idata-poc
useApiKeys: "false"
cdc:
  enabled: "false"
  kafka:
    bootstrapServer: b-2.kafkadebezium.7zbc63.c25.kafka.us-east-1.amazonaws.com:9092
    groupId: idata-group
    topicPollingInterval: "1000"
  debezium:
    kafkaTopic: testdb-topic
  messageThreshold:
    objectStore: "10"
    redshift: "30"
    snowflake: "30"
aws:
  region: us-east-1
  secretsManager:
    apiKeysSecretName: idata-poc-api-keys
    snowflakeSecretName: idata-poc-snowflakesecrets
    redshiftSecretName: idata-poc-redshiftsecrets
    postgresSecretName: idata-poc-postgres
  sns:
    sendDatasetNotifications: "true"
    sendCDCNotifications: "false"
  sqs:
    ttlFileNotifierQueueMessages: "60"
    sendCDCMessageQueue: "false"