spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  server:
    tomcat:
      connection-timeout: "600000"
  management:
    health:
      probes:
        enabled: "true"
      livenessState:
        enabled: "true"
      readinessState:
        enabled: "true"
schedule:
  checkFileNotifierQueue: "5000"
  findJobsToStart: "5000"
  checkDatabaseSourceQueries: "30000"
environment: idata-poc
useApiKeys: "false"
cdc:
  enabled: "false"
  publishMessages:
    enabled: "false"
    sns:
      topicArn: na
  processMessages:
    enabled: "false"
    datasetMapperTableName: idata-poc-cdc-mapper
  writeMessageThreshold: # The threshold of messages received before the pipeline will create a file to process, instead of calling JDBC directly
    objectStore: "10"
    redshift: "30"
    snowflake: "30"
  debezium:
    enabled: "false"
    kafka:
      bootstrapServer: b-2.kafkadebezium.7zbc63.c25.kafka.us-east-1.amazonaws.com:9092
      groupId: idata-group
      topic: testdb-topic
      topicPollingInterval: "1000"
  idata:
    enabled: "true"
    type: mssql
    database:
      secretName: secret_here
      dbName: Billing
      includeTables:
        - dbo_BillingRecords_New
    pollingInterval: "5000"
    lastReadTableName: idata-poc-cdc-last-read
aws:
  region: us-east-1
  secretsManager:
    apiKeysSecretName: idata-poc-api-keys
    snowflakeSecretName: idata-poc-snowflakesecrets
    redshiftSecretName: idata-poc-redshiftsecrets
    postgresSecretName: idata-poc-postgres
  sns:
    sendDatasetNotifications: "true"
  sqs:
    ttlFileNotifierQueueMessages: "60"