spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  server:
    tomcat:
      connection-timeout: "600000"
  management:
    health:
      probes:
        enabled: "true"
      livenessState:
        enabled: "true"
      readinessState:
        enabled: "true"
schedule:
  checkFileNotifierQueue: "5000"
  findJobsToStart: "5000"
  checkDatabaseSourceQueries: "30000"
  checkCDCMessageQueue: "2000"
environment: idata-poc
useApiKeys: "false"
cdc:
  debezium:
    kafkaTopic: testdb-topic
aws:
  region: us-east-1
  secretsManager:
    apiKeysSecretName: idata-poc-api-keys
    snowflakeSecretName: idata-poc-snowflakesecrets
    redshiftSecretName: idata-redshiftsecrets
  sns:
    sendNotifications: "true"
  sqs:
    ttlFileNotifierQueueMessages: "60"