spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  server:
    tomcat:
      connection-timeout: "600000"
  management:
    health:
      probes:
        enabled: "true"
      livenessState:
        enabled: "true"
      readinessState:
        enabled: "true"
schedule:
  checkFileNotifierQueue: "5000"
  findJobsToStart: "5000"
  checkDatabaseSourceQueries: "30000"
  checkCDCMessageQueue: "10000"
environment: idata-poc
useApiKeys: "false"
spark:
  jobConfiguration:
    executorMemory: 8g
    executorCores: "1"
    numExecutors: "1"
    driverMemory: 5g
cdc:
  kafka:
    bootstrapServer: b-1.kafkadebezium.7zbc63.c25.kafka.us-east-1.amazonaws.com:9092
    groupId: idata-group
  debezium:
    kafkaTopic: testdb-topic
  messageThreshold:
    objectStore: 10
    redshift: 30
    snowflake: 30
aws:
  region: us-east-1
  secretsManager:
    apiKeysSecretName: idata-poc-api-keys
    snowflakeSecretName: idata-poc-snowflakesecrets
    redshiftSecretName: idata-poc-redshiftsecrets
  sns:
    sendDatasetNotifications: "true"
    sendCDCNotifications: "true"
  sqs:
    ttlFileNotifierQueueMessages: "60"
    sendCDCMessageQueue: "false"
  elasticMapReduce:
    emr:
      enabled: "true"
      masterNodeIp: "na"
    eksemr:
      enabled: "false"
      virtualClusterId: lf39nq0exg831vqoc7tz7894g
      executionRoleArn: arn:aws:iam::116279234263:role/EMRContainers-JobExecutionRole
      releaseLabel: emr-6.3.0-latest
      configurationFileUrl: s3://idata-poc-config/spark/emr-config.json
      cloudwatchLogGroupName: /eks-emr-logs/poc
      logUri: s3://idata-poc-temp/